### PR TITLE
Fix: Rename endpoint classes

### LINKED ISSUE #71: Rename the Payment class to PaymentMethods
The naming was due the plugin development was when Thawani Pay release there checkout service 
the payment endpoint is a new endpoint and paymentMethod is the old one. 

The naming was due easier calling if the development but now we have to rename the classes again

### PR DESCRIPTION
**Pull request by w7shdev**
closes #71 

## Description:

Thawani added a new endpoint called payment.
in This PR we are fixing the naming convection so each endpoint class will be targeting the exact endpoint. 

## Testing:

N/A

## Checklist

- [x] I have commented the newly added code
- [ ] I update the Readme.md file to include the new changes to the project
- [ ] All the previously included Unit Tests passed in all the cases

### CODE REVIEW

File: src/Endpoint/PaymentMethods.php [hunk 1]
```diff
@@ -5,7 +5,7 @@
 use \Thawani\RestAPI;
 
 /**
- * Thwawni gateWay Payment endpoint handler
+ * Thwawni gateWay Payment Methods endpoint handler
```
Comment (Ma7eer) [inline src/Endpoint/PaymentMethods.php:8]:
```suggestion
 * Thawani gateway Payment Methods endpoint handler
```

Noticed some more typos

**Review by Ma7eer — APPROVED** [review]
Looks good but noticed some minor typos. They are minor so I am approving. Just fix them and merge.
